defmodule Przma.CommonsCas.Repo.Migrations.CreateCasTable do
  @moduledoc """
  przma_commons_cas.cas_table — copy of the CAS metadata of PUBLIC files
  (one row per owner DID + content hash). Matches Przma.CommonsCas.CasRecord.

  Run with:  mix ecto.migrate -r Przma.CommonsCas.Repo
  """
  use Ecto.Migration

  def change do
    # id is a UUID generated by Ecto (CasRecord: @primary_key binary_id autogenerate)
    create_if_not_exists table(:cas_table, primary_key: false) do
      add :id, :binary_id, primary_key: true
      add :hash, :text, null: false
      add :did, :text, null: false
      add :mime_type, :text
      add :size_bytes, :bigint
      add :deleted_at, :utc_datetime_usec
      add :created_by, :text
      add :ref_count, :integer, null: false, default: 1
      add :is_encrypted, :boolean, null: false, default: false
      add :s3_uri, :text
      add :file_origin, :text

      timestamps(inserted_at: :created_at, updated_at: :updated_at, type: :utc_datetime_usec)
    end

    # One row per owner + content hash
    create_if_not_exists unique_index(:cas_table, [:did, :hash], name: :cas_table_did_hash_idx)
    create_if_not_exists index(:cas_table, [:hash], name: :cas_table_hash_idx)
  end
end