# lib/przma/deployment/home_instance.ex
#
# Home instance setup and validation utilities.
# Used by the setup wizard and przma-setup CLI tool.

defmodule PRZMA.Deployment.HomeInstance do
  require Logger

  @required_dirs ~w(vaults logs keys tmp)

  # ── SETUP WIZARD ────────────────────────────────────────────────────────

  @doc """
  Validate that the home instance is correctly configured.
  Returns {:ok, validation_report} or {:error, issues}.
  """
  def validate_setup do
    checks = [
      check_base_dir(),
      check_required_dirs(),
      check_phoenix_config(),
      check_ddns_agent(),
      check_tls_certificate(),
      check_encryption_keys(),
    ]

    issues  = Enum.filter(checks, fn c -> c.status == :error end)
    warnings = Enum.filter(checks, fn c -> c.status == :warning end)

    report = %{
      passed:   Enum.filter(checks, fn c -> c.status == :ok end),
      warnings: warnings,
      issues:   issues,
      ready:    Enum.empty?(issues),
    }

    if Enum.empty?(issues) do
      {:ok, report}
    else
      {:error, report}
    end
  end

  @doc "Generate a default Phoenix config for home instance"
  def generate_phoenix_config(opts \\ []) do
    instance_url = opts[:instance_url] || "https://alice.przma.net"
    did          = opts[:did]          || "did:web:alice.przma.net"
    base_path    = opts[:base_path]    || "/var/przma/vaults"

    """
    # config/runtime.exs — PRZMA Home Instance Configuration
    # Generated by przma-setup wizard

    import Config

    config :przma,
      deployment_mode:  :local,
      instance:         [url: "#{instance_url}"],
      vault: [
        base_path:      "#{base_path}",
        did:            "#{did}",
      ],
      encryption: [
        enabled:        true,
        key_source:     :file,
      ]

    config :przma, PRZMAWeb.Endpoint,
      url: [host: "#{URI.parse(instance_url).host}", scheme: "https"],
      https: [
        port:    443,
        certfile: "/etc/przma/tls/cert.pem",
        keyfile:  "/etc/przma/tls/key.pem",
      ]

    # PRZMA DDNS Agent (if using PRZMA DDNS)
    config :przma, PRZMA.Deployment.DDNSAgent,
      enabled:   true,
      subdomain: "#{URI.parse(instance_url).host}",
      did:       "#{did}"

    # Oban job queues
    config :przma, Oban,
      repo: PRZMA.Repo,
      queues: [
        default:      10,
        reminders:    5,
        circle_sync:  3,
        federation:   5,
        intelligence: 3,
      ]
    """
  end

  @doc "Generate systemd service unit for przma-ddns-agent"
  def generate_ddns_agent_systemd(subdomain, instance_url) do
    """
    [Unit]
    Description=PRZMA DDNS Agent
    After=network.target
    Wants=network.target

    [Service]
    Type=simple
    User=przma
    Group=przma
    WorkingDirectory=/opt/przma
    ExecStart=/usr/local/bin/przma-ddns-agent start
    Restart=always
    RestartSec=10
    Environment=PRZMA_SUBDOMAIN=#{subdomain}
    Environment=PRZMA_INSTANCE_URL=#{instance_url}
    Environment=PRZMA_LOCAL_PATH=/var/przma/vaults
    EnvironmentFile=/etc/przma/ddns-agent.env

    [Install]
    WantedBy=multi-user.target
    """
  end

  @doc "Generate mDNS service advertisement for LAN discovery"
  def mdns_service_record(instance_url, port \\ 4000) do
    host = URI.parse(instance_url).host
    %{
      name:     "_przma._tcp.local",
      type:     "PTR",
      value:    "#{host}._przma._tcp.local",
      hostname: "#{host}.local",
      port:     port,
      txt: [
        "version=1.0",
        "mode=home",
        "instance=#{instance_url}",
      ]
    }
  end

  # ── MULTI-USER PROVISIONING ──────────────────────────────────────────────

  @doc """
  Provision a new user account on the home instance.
  Creates vault directories and generates DID under instance domain.
  """
  def provision_user(username, instance_domain, base_path) do
    did        = "did:web:#{instance_domain}:users:#{username}"
    user_path  = Path.join(base_path, did |> String.replace(":", "_"))

    # Create user vault directories
    dirs = Enum.map(
      ~w(calendar/core calendar/commons chat/core files/core vault/core companion/core),
      fn ns -> Path.join(user_path, ns) end
    )

    Enum.each(dirs, fn dir ->
      File.mkdir_p!(dir)
    end)

    Logger.info("User provisioned on home instance",
      username: username, did: did, path: user_path)

    %{
      did:         did,
      vault_path:  user_path,
      username:    username,
      provisioned_at: DateTime.utc_now() |> DateTime.to_iso8601(),
    }
  end

  @doc "List all provisioned users on this home instance"
  def list_users(base_path) do
    case File.ls(base_path) do
      {:ok, entries} ->
        entries
        |> Enum.filter(fn e -> String.starts_with?(e, "did_web_") end)
        |> Enum.map(fn dir ->
            did = dir |> String.replace("did_web_", "did:web:") |> String.replace("_", ":")
            %{did: did, vault_path: Path.join(base_path, dir)}
          end)

      {:error, _} -> []
    end
  end

  # ── PRIVATE: VALIDATION CHECKS ───────────────────────────────────────────

  defp check_base_dir do
    base = Application.get_env(:przma, [:vault, :base_path], "/var/przma/vaults")
    if File.dir?(base) do
      %{check: :base_directory, status: :ok, message: "Vault base directory exists: #{base}"}
    else
      %{check: :base_directory, status: :error,
        message: "Vault base directory not found: #{base}. Run: mkdir -p #{base}"}
    end
  end

  defp check_required_dirs do
    base = Application.get_env(:przma, [:vault, :base_path], "/var/przma/vaults")
    missing = Enum.reject(@required_dirs, fn dir ->
      File.dir?(Path.join(Path.dirname(base), dir))
    end)

    if Enum.empty?(missing) do
      %{check: :required_dirs, status: :ok, message: "All required directories present"}
    else
      %{check: :required_dirs, status: :warning,
        message: "Some directories missing: #{Enum.join(missing, ", ")}"}
    end
  end

  defp check_phoenix_config do
    instance_url = Application.get_env(:przma, [:instance, :url])
    if instance_url do
      %{check: :phoenix_config, status: :ok, message: "Instance URL configured: #{instance_url}"}
    else
      %{check: :phoenix_config, status: :warning,
        message: "PRZMA_INSTANCE_URL not set — defaulting to https://przma.ai"}
    end
  end

  defp check_ddns_agent do
    # Check if PRZMA DDNS agent is running (systemd or process check)
    case System.cmd("pgrep", ["-f", "przma-ddns-agent"], stderr_to_stdout: true) do
      {_pid, 0} ->
        %{check: :ddns_agent, status: :ok, message: "przma-ddns-agent is running"}
      _ ->
        %{check: :ddns_agent, status: :warning,
          message: "przma-ddns-agent not running — home instance may not be reachable from internet"}
    end
  end

  defp check_tls_certificate do
    cert_path = "/etc/przma/tls/cert.pem"
    if File.exists?(cert_path) do
      # Check expiry using openssl
      case System.cmd("openssl", ["x509", "-enddate", "-noout", "-in", cert_path],
                     stderr_to_stdout: true) do
        {output, 0} ->
          %{check: :tls_certificate, status: :ok,
            message: "TLS certificate found. #{String.trim(output)}"}
        _ ->
          %{check: :tls_certificate, status: :warning, message: "TLS certificate unreadable"}
      end
    else
      %{check: :tls_certificate, status: :warning,
        message: "TLS certificate not found at #{cert_path}. Run: przma cert setup"}
    end
  end

  defp check_encryption_keys do
    key_dir = "/etc/przma/keys"
    if File.dir?(key_dir) and File.ls!(key_dir) != [] do
      %{check: :encryption_keys, status: :ok, message: "Encryption keys directory found"}
    else
      %{check: :encryption_keys, status: :warning,
        message: "No encryption keys configured. Run: przma encryption setup <did>"}
    end
  end
end
