[package]
name = "pzdb_nif"
version = "0.1.0"
edition = "2021"

[lib]
name = "pzdb_nif"
crate-type = ["cdylib"]

[dependencies]
rustler     = "0.30"
lancedb     = "0.5"
arrow-array = "50"
arrow-schema = "50"
tokio       = { version = "1", features = ["full"] }
serde_json  = "1"
uuid        = { version = "1", features = ["v4"] }
chrono = { version = "=0.4.38" }