[package]
name    = "przma_pzdb_nif"
version = "0.1.0"
edition = "2021"

[lib]
name       = "przma_pzdb_nif"
crate-type = ["cdylib"]

[dependencies]
rustler    = "0.36"
tokio      = { version = "1", features = ["rt", "rt-multi-thread", "macros"] }
serde_json = "1"
lancedb    = "0.9"
arrow-array  = "53"
arrow-schema = "53"
futures    = "0.3"
chrono     = "0.4"
uuid       = { version = "1", features = ["v4"] }
blake3     = "1"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
